### ISSUE TITLE
Potential modules for computational research

### ISSUE THREAD

**Issue by bensoltoff** [UC-MACSS/persp-research#1]
In no particular order:

* IRB
* Reproducibility in science
* Web data (APIs/web scraping)
* Synthesizing literature and writing a theory section
* Presenting results and analysis in a paper
* Identifying good papers vs. bad papers
* Designing a research poster
* Iterative analysis
    * How to best compare and evaluate different empirical models
    * p-hacking
    * Storing results in a lab notebook/tracking different iterations of the model
* **Bayesian non-parametric inference**
* Frequentist vs. bayesian inference
    * Compare the different schools of thought
    * Interpreting frequentist results vs. Bayesian results
* "Deep learning"
* Transitioning from exploratory/descriptive work to a final paper
* Running an experiment using Amazon Mechanical Turk
* Neural networks
* Hierarchical/multilevel data
* Estimating and interpreting interaction terms in regression analysis
    * [Brambor et al paper on interpreting interaction terms](http://localgov.fsu.edu/readings_papers/Research%20Methods/Brambor_et_al_Multipolicative_Interactions.pdf)
* OLS/GLM diagnostic tests

Plus an unknown number of workshops for refining their projects over the course of the term. Not sure we need to do one every week, but I can definitely see the use of 5-6 over the term

**Comment by bensoltoff** [comment]
* Time series data

**Comment by bensoltoff** [comment]
* Missing data and multiple imputation

**Comment by rickecon** [comment]
* Paper writing sections
  * Data section of paper
  * Theory section of paper
  * Estimation section of paper
  * Results or experiment section of paper
  * Introduction, Conclusion, Abstract
